<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div class="container">
        <div class="faqgroup-container">
            <?php 
                $faqGroupCollection = $block->getFaqGroupCollection();
                if($faqGroupCollection->getSize())
                {
                    foreach($faqGroupCollection as $faqGroup)
                    {
                        if($faqGroup->getStatus())
                        {
                            ?> 
                            <a class="faqgroup-section-title faqgroup-section" href="#faqgroup-<?=$faqGroup->getFaqgroupId();?>">
                                <div class="faqgroup-section-title-content">
                                    <img src="<?=$block->getMediaUrl().$faqGroup->getIcon();?>" width="40" height="40">
                                    <?=$faqGroup->getGroupname();?>
                                </div>
                            </a>                           
                            <?php
                        }
                    }
                }
                else
                {?>
                    <div class="faqgroup-section-title-content-empty">
                        No Faq Groups Available
                    </div>
                <?php
                }
            ?>
        </div>
        <div class="faq-container">
            <?php 
                if($faqGroupCollection->getSize())
                {
                    foreach($faqGroupCollection as $faqGroup)
                    {
                        if($faqGroup->getStatus())
                        {?>
                            <div class="faqgroup-section-content" id="faqgroup-<?=$faqGroup->getFaqgroupId();?>">                            
                                <span class="group-name"><?=$faqGroup->getGroupname();?></span>
                                <hr style="width:100%;margin-left:0">
                                <?php
                                    $faqCollection = $block->getFaqCollectionByGroupId($faqGroup->getFaqgroupId());
                                    if($faqCollection->getSize())
                                    {
                                        foreach($faqCollection as $faq)
                                        {
                                            if($faq->getStatus())
                                            {?>
                                                <div class="faq">
                                                    <div class="faq-section">
                                                        <a class="faq-section-title" href="#faq-<?=$faq->getFaqId();?>">
                                                            <?=$faq->getTitle();?>
                                                        </a>
                                                            <div id="faq-<?=$faq->getFaqId();?>" class="faq-section-content">
                                                                <?=$faq->getContent();?>
                                                            </div>                                            
                                                    </div>
                                                </div>
                                            <?php
                                            }
                                        }
                                    }
                                    else
                                    {?>
                                        <div class="faqgroup-section-title-content-empty">
                                            No Faq Available
                                        </div>
                                    <?php
                                    }?>
                            </div>
                        <?php
                        }
                    }
                }
            ?>
        </div>
        <div class="faq-ask-ques">Click to Ask A Question</div>
        <hr style="width:100%;margin-left:0">
        <div class="faq-add-new">
            <?php echo $this->getLayout()->createBlock("Bluethink\Faq\Block\Frontend\Faq\UserFaq")->setTemplate("Bluethink_Faq::faq_add_new.phtml")->toHtml() ?>
        </div>
    </div>
    
</body>
</html>
