<html>
<head>
<style>
td {
    padding-right: 10px;
}
tr:first-child {
  border-bottom: 1px solid grey;
}
.qtyCancel {
  margin: auto;
  width: 50%;
  border: 3px;
  padding: 10px;
}
</style>
</head>
<table>
    <tr>
        <td>Product</td>
        <td>ItemStatus</td>
        <td>Price</td>
        <td>Qty</td>
        <td>Row Total</td>
        <td>Qty Remaining</td>
        <td>Qty To Cancel</td>
    </tr>       
        <?php 
            $x=1; 
            foreach($block->getItemsCollection() as $item)
            {  
                if($item->getProductType()!='configurable')
                {
                    if($item->getParentItemId()!=null)
                    {
                       echo '<tr>
                                <td>'.$x.'.'.$item->getName().'<br>'.$item->getSku().'</td>
                                <td>Invoiced</td>
                                <td>'.$block->getFormattedPrice($item->getParentItem()->getBasePriceInclTax()).'</td>
                                <td>Ordered '.(int) $item->getQtyOrdered().'<br>';
                                if((int)$item->getQtyInvoiced()>0)
                                {
                                    echo 'Invoiced '.(int) $item->getQtyInvoiced().'<br>';
                                }
                                if((int)$item->getQtyCanceled()>0)
                                {
                                    echo 'Canceled '.(int) $item->getQtyCanceled();
                                }
                                echo '</td>
                                <td>'.$block->getFormattedPrice($item->getParentItem()->getBaseRowTotalInclTax()).'</td>
                                <td>'.(int) $item->getQtyInvoiced().'</td>
                                <td><div class="qtyCancel"><input type="text" id="item_data" name="item_data['.$item->getItemId().']" value="" size="1"/></div></td>
                                </tr>';
                                $x++;
                    }
                    else
                    {
                        echo '<tr>
                                <td>'.$x.'.'.$item->getName().'<br>'.$item->getSku().'</td>
                                <td>Invoiced</td>
                                <td>'.$block->getFormattedPrice($item->getBasePriceInclTax()).'</td>
                                <td>Ordered '.(int) $item->getQtyOrdered().'<br>';
                                if((int)$item->getQtyInvoiced()>0)
                                {
                                    echo 'Invoiced '.(int) $item->getQtyInvoiced().'<br>';
                                }
                                if((int)$item->getQtyCanceled()>0)
                                {
                                    echo 'Canceled '.(int) $item->getQtyCanceled();
                                }
                                echo '</td>
                                <td>'.$block->getFormattedPrice($item->getBaseRowTotalInclTax()).'</td>
                                <td>'.(int) $item->getQtyInvoiced().'</td>
                                <td><div class="qtyCancel"><input type="text" id="item_data" name="item_data['.$item->getItemId().']" value="" size="1"/></div></td>
                                </tr>';
                                $x++;
                    }
                }
            }?>
</table>
</html>