<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <th>Product</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Tax Amount</th>
                <th>Discount Amount</th>
                <th>Row Total</th>
            </tr>
        </thead>
        <?php $_items = $block->getCancelItemsCollection();?>
        <?php $i=0;foreach ($_items as $_item)
        {$i++;?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
                <tr>
                    <td><?php echo $_item->getName()."<br>"."SKU:".$_item->getSku();?></td>
                    <td><?php echo $_item->getPrice();?></td>
                    <td><?php echo $_item->getQty();?></td>
                    <td><?php echo $_item->getTaxAmount();?></td>
                    <td><?php echo $_item->getDiscountAmount();?></td>
                    <td><?php echo $_item->getRowTotalInclTax();?></td>
                </tr>
            </tbody><?php            
        }?>
    </table>
</div>